### ISSUE TITLE
Powershell

### ISSUE THREAD

**Issue by PapaSpik3** [gheeres/Ricoh.NET#5]
Hello is it possible to you it with powershell?

There is no dll available to import :(

**Comment by gheeres** [comment]
Yes, it should work with PowerShell.

You can create the DLL by compiling it with a .NET compiler; the [VisualStudio IDE](https://www.visualstudio.com/en-us/visual-studio-homepage-vs.aspx) being a logical choice.  Otherwise, you can download the NuGet package (which is basically a .zip file). Inside the contents of the file, you'll find the Ricoh.NET DLL.

https://www.nuget.org/packages/Ricoh.NET/
Direct download (v0.1.0): https://www.nuget.org/api/v2/package/Ricoh.NET/0.1.0
